cm_rerun:
    cluster: cm_rerun_cluster
    data_center: op-us-east-1


default:
    cluster: mrp
    data_center: op-us-east-1


services_names:
    active_namenode: active.namenode
    hdfs_namenode: hdfs-namenode
    redis_bigdata: redis-bigdata










